name = "frontierlegends"
main = "./gunslinger/src/worker.js"
compatibility_date = "2024-11-01"

[assets]
directory = "./gunslinger/public"
binding = "ASSETS"

[durable_objects]
bindings = [
  { name = "MATCHMAKER", class_name = "Matchmaker" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Matchmaker"]
